server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querytest?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: 1Q2w3e4r5t!@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  ## org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
    show_sql: true
